/**
 * Vitest golden tests for src/engine/indicators.ts
 *
 * Golden values were generated by running the prototype's data.js logic in
 * Node.js with mulberry32(42) as the PRNG seed and 30 synthetic bars.
 * The fixture is committed at src/engine/__fixtures__/indicators.fixture.json.
 */
import { describe, it, expect } from 'vitest';
import { sma, ema, bollinger, rsi, toHeikinAshi, parseUserSeries, fmtPrice, fmtPct, donchian, atr } from './indicators';
import fixture from './__fixtures__/indicators.fixture.json';
import type { Bar } from '../data/MarketDataProvider';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const EPSILON = 1e-9;

function closeEnough(a: number | null, b: number | null, eps = EPSILON): boolean {
  if (a === null && b === null) return true;
  if (a === null || b === null) return false;
  return Math.abs(a - b) < eps;
}

function assertArrayClose(
  actual: (number | null)[],
  expected: (number | null)[],
  eps = EPSILON,
): void {
  expect(actual.length).toBe(expected.length);
  actual.forEach((v, i) => {
    expect(closeEnough(v, expected[i], eps)).toBe(true);
  });
}

// ---------------------------------------------------------------------------
// Test data from fixture
// ---------------------------------------------------------------------------

const bars = fixture.bars as Bar[];
const closes = bars.map((b) => b.c);

// ---------------------------------------------------------------------------
// SMA
// ---------------------------------------------------------------------------

describe('sma', () => {
  it('golden: sma(closes, 5) matches fixture', () => {
    const result = sma(closes, 5);
    assertArrayClose(result, fixture.sma5);
  });

  it('first (period-1) values are null', () => {
    const result = sma(closes, 5);
    for (let i = 0; i < 4; i++) expect(result[i]).toBeNull();
    expect(result[4]).not.toBeNull();
  });

  it('period 1 equals the input', () => {
    const result = sma(closes, 1);
    result.forEach((v, i) => {
      expect(v).not.toBeNull();
      expect(closeEnough(v, closes[i])).toBe(true);
    });
  });

  it('returns all nulls for period > length', () => {
    const result = sma([1, 2], 5);
    result.forEach((v) => expect(v).toBeNull());
  });
});

// ---------------------------------------------------------------------------
// EMA
// ---------------------------------------------------------------------------

describe('ema', () => {
  it('golden: ema(closes, 5) matches fixture', () => {
    const result = ema(closes, 5);
    assertArrayClose(result, fixture.ema5);
  });

  it('first value equals closes[0]', () => {
    const result = ema(closes, 5);
    expect(closeEnough(result[0], closes[0])).toBe(true);
  });

  it('every position has a value (no nulls)', () => {
    const result = ema(closes, 5);
    result.forEach((v) => expect(v).not.toBeNull());
  });
});

// ---------------------------------------------------------------------------
// Bollinger Bands
// ---------------------------------------------------------------------------

describe('bollinger', () => {
  it('golden: bollinger(closes, 5, 2) matches fixture', () => {
    const result = bollinger(closes, 5, 2);
    assertArrayClose(result.mid, fixture.bollinger5.mid);
    assertArrayClose(result.upper, fixture.bollinger5.upper);
    assertArrayClose(result.lower, fixture.bollinger5.lower);
  });

  it('upper > mid and lower < mid where not null', () => {
    const result = bollinger(closes, 5, 2);
    result.upper.forEach((u, i) => {
      const m = result.mid[i];
      const l = result.lower[i];
      if (u !== null && m !== null && l !== null) {
        expect(u).toBeGreaterThan(m);
        expect(l).toBeLessThan(m);
      }
    });
  });

  it('band width ≥ 0 everywhere', () => {
    const result = bollinger(closes, 5, 2);
    result.upper.forEach((u, i) => {
      const l = result.lower[i];
      if (u !== null && l !== null) {
        expect(u - l).toBeGreaterThanOrEqual(0);
      }
    });
  });
});

// ---------------------------------------------------------------------------
// RSI
// ---------------------------------------------------------------------------

describe('rsi', () => {
  it('golden: rsi(closes, 5) matches fixture', () => {
    const result = rsi(closes, 5);
    assertArrayClose(result, fixture.rsi5);
  });

  it('golden: rsi(closes, 14) matches fixture', () => {
    const result = rsi(closes, 14);
    assertArrayClose(result, fixture.rsi14);
  });

  it('all non-null values are in [0, 100]', () => {
    const result = rsi(closes, 5);
    result.filter((v) => v !== null).forEach((v) => {
      expect(v as number).toBeGreaterThanOrEqual(0);
      expect(v as number).toBeLessThanOrEqual(100);
    });
  });

  it('first (period) values are null', () => {
    const result = rsi(closes, 5);
    for (let i = 0; i < 5; i++) expect(result[i]).toBeNull();
    expect(result[5]).not.toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Heikin-Ashi
// ---------------------------------------------------------------------------

describe('toHeikinAshi', () => {
  it('golden: toHeikinAshi(bars) matches fixture', () => {
    const result = toHeikinAshi(bars);
    expect(result.length).toBe(fixture.heikinAshi.length);
    result.forEach((bar, i) => {
      const exp = fixture.heikinAshi[i] as Bar;
      expect(bar.ts).toBe(exp.ts);
      expect(closeEnough(bar.o, exp.o)).toBe(true);
      expect(closeEnough(bar.h, exp.h)).toBe(true);
      expect(closeEnough(bar.l, exp.l)).toBe(true);
      expect(closeEnough(bar.c, exp.c)).toBe(true);
      expect(closeEnough(bar.v, exp.v)).toBe(true);
    });
  });

  it('haC = (o+h+l+c)/4 for every bar', () => {
    const result = toHeikinAshi(bars);
    result.forEach((ha, i) => {
      const src = bars[i];
      const expectedC = (src.o + src.h + src.l + src.c) / 4;
      expect(closeEnough(ha.c, expectedC)).toBe(true);
    });
  });

  it('first bar haO = (o+c)/2', () => {
    const result = toHeikinAshi(bars);
    const expectedO = (bars[0].o + bars[0].c) / 2;
    expect(closeEnough(result[0].o, expectedO)).toBe(true);
  });

  it('high >= max(h, haO, haC) for every bar', () => {
    const result = toHeikinAshi(bars);
    result.forEach((ha, i) => {
      const src = bars[i];
      expect(ha.h).toBeGreaterThanOrEqual(src.h - EPSILON);
      expect(ha.h).toBeGreaterThanOrEqual(ha.o - EPSILON);
      expect(ha.h).toBeGreaterThanOrEqual(ha.c - EPSILON);
    });
  });

  it('preserves ts and v from source bars', () => {
    const result = toHeikinAshi(bars);
    result.forEach((ha, i) => {
      expect(ha.ts).toBe(bars[i].ts);
      expect(ha.v).toBe(bars[i].v);
    });
  });
});

// ---------------------------------------------------------------------------
// parseUserSeries — error-path coverage
// ---------------------------------------------------------------------------

describe('parseUserSeries', () => {
  it('empty string returns empty series, no errors', () => {
    const r = parseUserSeries('');
    expect(r.series).toEqual([]);
    expect(r.errors).toEqual([]);
  });

  it('whitespace-only returns empty series, no errors', () => {
    const r = parseUserSeries('   \n\n  ');
    expect(r.series).toEqual([]);
    expect(r.errors).toEqual([]);
  });

  it('multi-line CSV parses correctly', () => {
    const input = '1.0,2.0,3.0\n4.0,5.0';
    const r = parseUserSeries(input);
    expect(r.series).toEqual([1, 2, 3, 4, 5]);
    expect(r.errors).toEqual([]);
  });

  it('mixed whitespace and semicolons as delimiters', () => {
    const input = '10; 20\t30\n 40 ';
    const r = parseUserSeries(input);
    expect(r.series).toEqual([10, 20, 30, 40]);
    expect(r.errors).toEqual([]);
  });

  it('blank lines are silently skipped', () => {
    const input = '1\n\n\n2\n\n3';
    const r = parseUserSeries(input);
    expect(r.series).toEqual([1, 2, 3]);
    expect(r.errors).toEqual([]);
  });

  it('malformed token on line 3 is reported', () => {
    const input = '1.0\n2.0\nabc\n4.0';
    const r = parseUserSeries(input);
    expect(r.series).toEqual([1, 2, 4]);
    expect(r.errors.length).toBe(1);
    expect(r.errors[0]).toMatch(/line 3/);
    expect(r.errors[0]).toMatch(/abc/);
  });

  it('multiple malformed tokens are each reported', () => {
    const input = 'foo,1,bar\n2,baz';
    const r = parseUserSeries(input);
    expect(r.series).toEqual([1, 2]);
    expect(r.errors.length).toBe(3);
    expect(r.errors[0]).toMatch(/line 1.*foo/);
    expect(r.errors[1]).toMatch(/line 1.*bar/);
    expect(r.errors[2]).toMatch(/line 2.*baz/);
  });

  it('valid JSON array is parsed', () => {
    const input = '[1.5, 2.5, 3.5]';
    const r = parseUserSeries(input);
    expect(r.series).toEqual([1.5, 2.5, 3.5]);
    expect(r.errors).toEqual([]);
  });

  it('invalid JSON reports error', () => {
    const input = '[1, 2, ]';
    const r = parseUserSeries(input);
    expect(r.errors.length).toBeGreaterThan(0);
  });

  it('single number on its own line', () => {
    const r = parseUserSeries('42');
    expect(r.series).toEqual([42]);
    expect(r.errors).toEqual([]);
  });

  it('negative numbers are parsed', () => {
    const r = parseUserSeries('-1.5, -2.3');
    expect(r.series[0]).toBeCloseTo(-1.5);
    expect(r.series[1]).toBeCloseTo(-2.3);
  });
});

// ---------------------------------------------------------------------------
// fmtPrice
// ---------------------------------------------------------------------------

describe('fmtPrice', () => {
  it('returns — for Infinity', () => {
    expect(fmtPrice(Infinity)).toBe('—');
    expect(fmtPrice(-Infinity)).toBe('—');
    expect(fmtPrice(NaN)).toBe('—');
  });

  it('>= 10000: integer formatting (no decimals)', () => {
    const s = fmtPrice(67400);
    expect(s.includes('.')).toBe(false);
  });

  it('>= 1000: one decimal', () => {
    const s = fmtPrice(3420);
    const parts = s.split('.');
    expect(parts[1]).toHaveLength(1);
  });

  it('>= 100: two decimals', () => {
    const s = fmtPrice(178);
    const parts = s.split('.');
    expect(parts[1]).toHaveLength(2);
  });

  it('>= 1: three decimals (toFixed)', () => {
    const s = fmtPrice(9.4);
    expect(s.endsWith('4.400') || s === '9.400').toBeTruthy();
    expect(s.split('.')[1]).toHaveLength(3);
  });

  it('>= 0.01: four decimals', () => {
    const s = fmtPrice(0.142);
    expect(s.split('.')[1]).toHaveLength(4);
  });

  it('< 0.01: six decimals', () => {
    const s = fmtPrice(0.00012);
    expect(s.split('.')[1]).toHaveLength(6);
  });

  it('explicit decimals override auto', () => {
    const s = fmtPrice(1234.5678, 2);
    expect(s).toBe('1234.57');
  });
});

// ---------------------------------------------------------------------------
// fmtPct
// ---------------------------------------------------------------------------

describe('fmtPct', () => {
  it('positive value has + prefix', () => {
    expect(fmtPct(0.0245)).toBe('+2.45%');
  });

  it('negative value has - prefix, no + prefix', () => {
    const s = fmtPct(-0.0081);
    expect(s.startsWith('-')).toBe(true);
    expect(s).toBe('-0.81%');
  });

  it('zero has no + prefix', () => {
    expect(fmtPct(0)).toBe('0.00%');
  });

  it('two decimal places always', () => {
    const s = fmtPct(0.1);
    expect(s.split('.')[1]).toHaveLength(3); // "00%"
  });
});

// ---------------------------------------------------------------------------
// Donchian (W5-A)
// ---------------------------------------------------------------------------

describe('donchian', () => {
  function bar(h: number, l: number): Bar {
    return { ts: 0, o: l, h, l, c: l, v: 1 };
  }

  it('returns null until period bars seen, then highest-high / lowest-low', () => {
    const bs: Bar[] = [
      bar(10, 5),
      bar(12, 4),
      bar(11, 6),
      bar(15, 7),
      bar(14, 9),
    ];
    const { high, low } = donchian(bs, 3);
    expect(high.slice(0, 2)).toEqual([null, null]);
    expect(low.slice(0, 2)).toEqual([null, null]);
    // bars 0..2: highs [10,12,11] → 12; lows [5,4,6] → 4
    expect(high[2]).toBe(12);
    expect(low[2]).toBe(4);
    // bars 1..3: highs [12,11,15] → 15; lows [4,6,7] → 4
    expect(high[3]).toBe(15);
    expect(low[3]).toBe(4);
    // bars 2..4: highs [11,15,14] → 15; lows [6,7,9] → 6
    expect(high[4]).toBe(15);
    expect(low[4]).toBe(6);
  });

  it('handles period === bars.length', () => {
    const bs: Bar[] = [bar(10, 5), bar(12, 4), bar(11, 6)];
    const { high, low } = donchian(bs, 3);
    expect(high).toEqual([null, null, 12]);
    expect(low).toEqual([null, null, 4]);
  });
});

// ---------------------------------------------------------------------------
// ATR (W5-A) — Wilder's smoothing
// ---------------------------------------------------------------------------

describe('atr', () => {
  it('seeds with mean of first `period` TRs, then Wilder-smooths', () => {
    // Simple, fully-deterministic 5-bar series with period=3.
    // bar 0: h=10 l=8 c=9 → tr0 = 10-8 = 2
    // bar 1: h=12 l=9  c=11, prevC=9  → tr1 = max(3, 3, 0) = 3
    // bar 2: h=13 l=10 c=12, prevC=11 → tr2 = max(3, 2, 1) = 3
    // bar 3: h=14 l=11 c=13, prevC=12 → tr3 = max(3, 2, 1) = 3
    // bar 4: h=15 l=12 c=14, prevC=13 → tr4 = max(3, 2, 1) = 3
    const bs: Bar[] = [
      { ts: 0, o: 8,  h: 10, l: 8,  c: 9,  v: 1 },
      { ts: 1, o: 9,  h: 12, l: 9,  c: 11, v: 1 },
      { ts: 2, o: 11, h: 13, l: 10, c: 12, v: 1 },
      { ts: 3, o: 12, h: 14, l: 11, c: 13, v: 1 },
      { ts: 4, o: 13, h: 15, l: 12, c: 14, v: 1 },
    ];
    const result = atr(bs, 3);
    expect(result[0]).toBeNull();
    expect(result[1]).toBeNull();
    // Seed: mean(2,3,3) = 8/3
    expect(result[2]).toBeCloseTo(8 / 3, 12);
    // Wilder: ((8/3)*2 + 3) / 3 = (16/3 + 3)/3 = (25/3)/3 = 25/9
    expect(result[3]).toBeCloseTo(25 / 9, 12);
    // Next: ((25/9)*2 + 3) / 3 = (50/9 + 27/9)/3 = (77/9)/3 = 77/27
    expect(result[4]).toBeCloseTo(77 / 27, 12);
  });

  it('returns all-null when bars.length < period', () => {
    const bs: Bar[] = [{ ts: 0, o: 1, h: 1, l: 1, c: 1, v: 1 }];
    expect(atr(bs, 14)).toEqual([null]);
  });
});
