//! src-tauri/src/ai_workspace.rs — DAO layer for AI workspace tables (Step 2)
//!
//! Tables introduced by migration 0010_ai_workspace_tables.sql:
//!   `research_notes`, `ai_datasets`, `ai_strategies`, `strategy_revisions`,
//!   `paper_positions`, `paper_fills`.
//!
//! **No Tauri commands live here.** This is pure data-access logic that will be
//! consumed by the MCP bridge (Step 4 / Step 6) and the Strategy Artifact Panel
//! (Step 11b).  The public surface follows the same conventions as
//! `commands/db.rs`:
//!   - Each table exposes insert / get / list / update / delete helpers.
//!   - All functions take `&rusqlite::Connection` and propagate errors via `?`.
//!   - Structs derive `Debug`, `Clone`, `Serialize`, `Deserialize`.
//!   - Time stamps are unix milliseconds (i64), consistent with other tables.
//!
//! **Append-only invariant (ADR-0005):** `update_strategy` MUST insert a new
//! `strategy_revisions` row with `rev = current_revision + 1` and then UPDATE
//! `ai_strategies`.  It MUST NOT mutate any existing `strategy_revisions` row.

// All public items in this module are pre-wired for the MCP bridge (Step 4/6)
// and Strategy Artifact Panel (Step 11b); they are intentionally unused until
// those steps wire them into commands/. Suppressing dead_code for the whole
// module avoids noisy per-item attributes.
#![allow(dead_code)]

use rusqlite::{Connection, params};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

// ---------------------------------------------------------------------------
// ResearchNote
// ---------------------------------------------------------------------------

/// One research note, optionally tagged and bound to a symbol + timeframe.
/// Mirrors the `research_notes` table introduced in migration 0010.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResearchNote {
    pub id: String,
    pub title: String,
    pub body: String,
    /// JSON array string, e.g. `'["DeFi","momentum"]'`.
    pub tags_json: String,
    pub symbol: Option<String>,
    pub timeframe: Option<String>,
    /// Unix milliseconds.
    pub created_at: i64,
}

/// Insert a new research note. `id` must be a stable UUID generated by the
/// caller (the TS side or the MCP bridge).
pub fn research_note_insert(conn: &Connection, note: &ResearchNote) -> rusqlite::Result<()> {
    conn.execute(
        "INSERT INTO research_notes (id, title, body, tags_json, symbol, timeframe, created_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
        params![
            note.id,
            note.title,
            note.body,
            note.tags_json,
            note.symbol,
            note.timeframe,
            note.created_at,
        ],
    )?;
    Ok(())
}

/// Return all research notes ordered by `created_at DESC`.
pub fn research_note_list(conn: &Connection) -> rusqlite::Result<Vec<ResearchNote>> {
    let mut stmt = conn.prepare(
        "SELECT id, title, body, tags_json, symbol, timeframe, created_at
         FROM research_notes
         ORDER BY created_at DESC",
    )?;
    let rows = stmt.query_map([], |row| {
        Ok(ResearchNote {
            id: row.get(0)?,
            title: row.get(1)?,
            body: row.get(2)?,
            tags_json: row.get(3)?,
            symbol: row.get(4)?,
            timeframe: row.get(5)?,
            created_at: row.get(6)?,
        })
    })?
    .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

/// Fetch one note by primary key. Returns `None` when the id is unknown.
pub fn research_note_get(conn: &Connection, id: &str) -> rusqlite::Result<Option<ResearchNote>> {
    let result = conn.query_row(
        "SELECT id, title, body, tags_json, symbol, timeframe, created_at
         FROM research_notes WHERE id = ?1",
        params![id],
        |row| {
            Ok(ResearchNote {
                id: row.get(0)?,
                title: row.get(1)?,
                body: row.get(2)?,
                tags_json: row.get(3)?,
                symbol: row.get(4)?,
                timeframe: row.get(5)?,
                created_at: row.get(6)?,
            })
        },
    );
    match result {
        Ok(r) => Ok(Some(r)),
        Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
        Err(e) => Err(e),
    }
}

/// Delete a research note by id. No-op when id doesn't exist.
pub fn research_note_delete(conn: &Connection, id: &str) -> rusqlite::Result<()> {
    conn.execute("DELETE FROM research_notes WHERE id = ?1", params![id])?;
    Ok(())
}

// ---------------------------------------------------------------------------
// AiDataset — richer than the existing `datasets` blob table.
// ---------------------------------------------------------------------------

/// Structured dataset record in the `ai_datasets` table.
/// `kind` mirrors `Dataset.kind` in `src/ai/schemas.ts` — `'overlay'` or `'series'`.
/// `source` is `'ai'`, `'upload'`, or `'user'`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiDataset {
    pub id: String,
    pub name: String,
    pub symbol: String,
    pub timeframe: String,
    /// `'overlay'` | `'series'`
    pub kind: String,
    /// JSON-serialised `Dataset.values` array from `src/ai/schemas.ts`.
    pub values_json: String,
    /// `'ai'` | `'upload'` | `'user'`
    pub source: String,
    /// Unix milliseconds.
    pub created_at: i64,
}

/// Insert a new AI dataset record. `id` must be a caller-generated UUID.
pub fn ai_dataset_insert(conn: &Connection, ds: &AiDataset) -> rusqlite::Result<()> {
    conn.execute(
        "INSERT INTO ai_datasets
             (id, name, symbol, timeframe, kind, values_json, source, created_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
        params![
            ds.id,
            ds.name,
            ds.symbol,
            ds.timeframe,
            ds.kind,
            ds.values_json,
            ds.source,
            ds.created_at,
        ],
    )?;
    Ok(())
}

/// Return all AI datasets ordered by `(symbol, timeframe, created_at)`.
pub fn ai_dataset_list(conn: &Connection) -> rusqlite::Result<Vec<AiDataset>> {
    let mut stmt = conn.prepare(
        "SELECT id, name, symbol, timeframe, kind, values_json, source, created_at
         FROM ai_datasets
         ORDER BY symbol ASC, timeframe ASC, created_at ASC",
    )?;
    let rows = stmt.query_map([], |row| {
        Ok(AiDataset {
            id: row.get(0)?,
            name: row.get(1)?,
            symbol: row.get(2)?,
            timeframe: row.get(3)?,
            kind: row.get(4)?,
            values_json: row.get(5)?,
            source: row.get(6)?,
            created_at: row.get(7)?,
        })
    })?
    .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

/// Fetch one AI dataset by primary key. Returns `None` when unknown.
pub fn ai_dataset_get(conn: &Connection, id: &str) -> rusqlite::Result<Option<AiDataset>> {
    let result = conn.query_row(
        "SELECT id, name, symbol, timeframe, kind, values_json, source, created_at
         FROM ai_datasets WHERE id = ?1",
        params![id],
        |row| {
            Ok(AiDataset {
                id: row.get(0)?,
                name: row.get(1)?,
                symbol: row.get(2)?,
                timeframe: row.get(3)?,
                kind: row.get(4)?,
                values_json: row.get(5)?,
                source: row.get(6)?,
                created_at: row.get(7)?,
            })
        },
    );
    match result {
        Ok(r) => Ok(Some(r)),
        Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
        Err(e) => Err(e),
    }
}

/// Delete an AI dataset by id. No-op when id doesn't exist.
pub fn ai_dataset_delete(conn: &Connection, id: &str) -> rusqlite::Result<()> {
    conn.execute("DELETE FROM ai_datasets WHERE id = ?1", params![id])?;
    Ok(())
}

// ---------------------------------------------------------------------------
// AiStrategy + StrategyRevision — append-only revision tracking.
// ---------------------------------------------------------------------------

/// Head record for a strategy. `body_json` always holds the DSL JSON of
/// `current_revision`. `strategy_revisions` holds the full history.
///
/// Mirrors the `ai_strategies` table (migration 0010).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiStrategy {
    pub id: String,
    pub name: String,
    /// JSON-encoded Strategy DSL (see `src/ai/schemas.ts` for the shape).
    pub body_json: String,
    pub current_revision: i64,
    /// Unix milliseconds.
    pub created_at: i64,
    /// Unix milliseconds — updated on every `update_strategy` call.
    pub updated_at: i64,
}

/// One immutable snapshot in the `strategy_revisions` table.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyRevision {
    pub id: String,
    pub strategy_id: String,
    pub rev: i64,
    pub body_json: String,
    /// Unix milliseconds.
    pub created_at: i64,
}

/// Insert a brand-new strategy and its first revision (`rev = 1`) atomically.
///
/// The caller supplies a pre-generated UUID for both `strategy.id` and
/// `rev_id` (the revision row's primary key).
pub fn strategy_insert(
    conn: &Connection,
    strategy: &AiStrategy,
    rev_id: &str,
) -> rusqlite::Result<()> {
    // Wrap both inserts in a single transaction so a crash can't leave
    // `ai_strategies` without its matching revision row.
    let tx = conn.unchecked_transaction()?;
    conn.execute(
        "INSERT INTO ai_strategies
             (id, name, body_json, current_revision, created_at, updated_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        params![
            strategy.id,
            strategy.name,
            strategy.body_json,
            strategy.current_revision,
            strategy.created_at,
            strategy.updated_at,
        ],
    )?;
    conn.execute(
        "INSERT INTO strategy_revisions (id, strategy_id, rev, body_json, created_at)
         VALUES (?1, ?2, ?3, ?4, ?5)",
        params![
            rev_id,
            strategy.id,
            strategy.current_revision,
            strategy.body_json,
            strategy.created_at,
        ],
    )?;
    tx.commit()?;
    Ok(())
}

/// Return all strategies ordered by `updated_at DESC`.
pub fn strategy_list(conn: &Connection) -> rusqlite::Result<Vec<AiStrategy>> {
    let mut stmt = conn.prepare(
        "SELECT id, name, body_json, current_revision, created_at, updated_at
         FROM ai_strategies
         ORDER BY updated_at DESC",
    )?;
    let rows = stmt.query_map([], |row| {
        Ok(AiStrategy {
            id: row.get(0)?,
            name: row.get(1)?,
            body_json: row.get(2)?,
            current_revision: row.get(3)?,
            created_at: row.get(4)?,
            updated_at: row.get(5)?,
        })
    })?
    .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

/// Fetch one strategy by primary key. Returns `None` when unknown.
pub fn strategy_get(conn: &Connection, id: &str) -> rusqlite::Result<Option<AiStrategy>> {
    let result = conn.query_row(
        "SELECT id, name, body_json, current_revision, created_at, updated_at
         FROM ai_strategies WHERE id = ?1",
        params![id],
        |row| {
            Ok(AiStrategy {
                id: row.get(0)?,
                name: row.get(1)?,
                body_json: row.get(2)?,
                current_revision: row.get(3)?,
                created_at: row.get(4)?,
                updated_at: row.get(5)?,
            })
        },
    );
    match result {
        Ok(r) => Ok(Some(r)),
        Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
        Err(e) => Err(e),
    }
}

/// Update a strategy with a new body — **append-only** (ADR-0005).
///
/// 1. Reads `current_revision` from `ai_strategies`.
/// 2. Inserts a NEW `strategy_revisions` row with `rev = current_revision + 1`.
/// 3. Updates `ai_strategies.body_json`, `current_revision`, and `updated_at`.
///
/// Returns the updated `AiStrategy` head record.  Errors if the id is unknown.
///
/// The caller must supply a unique `rev_id` for the new revision row.
pub fn strategy_update(
    conn: &Connection,
    id: &str,
    new_body_json: &str,
    rev_id: &str,
) -> rusqlite::Result<AiStrategy> {
    let tx = conn.unchecked_transaction()?;

    // 1. Read the current revision number — errors with QueryReturnedNoRows if
    //    the strategy doesn't exist, which is the correct behaviour.
    let current_revision: i64 = conn.query_row(
        "SELECT current_revision FROM ai_strategies WHERE id = ?1",
        params![id],
        |row| row.get(0),
    )?;

    let next_rev = current_revision + 1;
    let updated_at = now_ms();

    // 2. Append a new revision row — NEVER mutate an existing one.
    conn.execute(
        "INSERT INTO strategy_revisions (id, strategy_id, rev, body_json, created_at)
         VALUES (?1, ?2, ?3, ?4, ?5)",
        params![rev_id, id, next_rev, new_body_json, updated_at],
    )?;

    // 3. Update the head record.
    conn.execute(
        "UPDATE ai_strategies
         SET body_json = ?1, current_revision = ?2, updated_at = ?3
         WHERE id = ?4",
        params![new_body_json, next_rev, updated_at, id],
    )?;

    tx.commit()?;

    // Re-fetch to return the canonical, post-commit state.
    // We know the row exists (we just updated it) so unwrap is safe here.
    let updated = strategy_get(conn, id)?.expect("strategy disappeared after update");
    Ok(updated)
}

/// Delete a strategy and all its revisions (cascade enforced by FK).
/// No-op when id doesn't exist.
pub fn strategy_delete(conn: &Connection, id: &str) -> rusqlite::Result<()> {
    conn.execute("DELETE FROM ai_strategies WHERE id = ?1", params![id])?;
    Ok(())
}

/// Return all revision rows for a strategy, ordered by `rev ASC`.
pub fn strategy_revisions_list(
    conn: &Connection,
    strategy_id: &str,
) -> rusqlite::Result<Vec<StrategyRevision>> {
    let mut stmt = conn.prepare(
        "SELECT id, strategy_id, rev, body_json, created_at
         FROM strategy_revisions
         WHERE strategy_id = ?1
         ORDER BY rev ASC",
    )?;
    let rows = stmt.query_map(params![strategy_id], |row| {
        Ok(StrategyRevision {
            id: row.get(0)?,
            strategy_id: row.get(1)?,
            rev: row.get(2)?,
            body_json: row.get(3)?,
            created_at: row.get(4)?,
        })
    })?
    .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

// ---------------------------------------------------------------------------
// PaperPosition + PaperFill — paper-trade ledger.
// ---------------------------------------------------------------------------

/// One paper-trade position in the `paper_positions` table.
/// `side` is `'long'` or `'short'`.
/// `closed_at` and `close_price` are `None` while the position is open.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaperPosition {
    pub id: String,
    pub symbol: String,
    /// `'long'` | `'short'`
    pub side: String,
    pub qty: f64,
    pub ref_price: f64,
    /// Unix milliseconds.
    pub opened_at: i64,
    /// Unix milliseconds. `None` while open.
    pub closed_at: Option<i64>,
    pub close_price: Option<f64>,
}

/// One fill event in the `paper_fills` table.
/// `kind` is `'open'`, `'close'`, or `'adjust'`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaperFill {
    pub id: String,
    pub position_id: String,
    /// Unix milliseconds.
    pub ts: i64,
    pub qty: f64,
    pub price: f64,
    /// `'open'` | `'close'` | `'adjust'`
    pub kind: String,
}

/// Open a new paper position and insert the corresponding `'open'` fill
/// atomically.  Returns the inserted position.
///
/// `fill_id` must be a caller-generated UUID for the fill row.
pub fn paper_position_open(
    conn: &Connection,
    position: &PaperPosition,
    fill_id: &str,
) -> rusqlite::Result<()> {
    let tx = conn.unchecked_transaction()?;
    conn.execute(
        "INSERT INTO paper_positions
             (id, symbol, side, qty, ref_price, opened_at, closed_at, close_price)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
        params![
            position.id,
            position.symbol,
            position.side,
            position.qty,
            position.ref_price,
            position.opened_at,
            position.closed_at,
            position.close_price,
        ],
    )?;
    // Insert the matching open fill.
    conn.execute(
        "INSERT INTO paper_fills (id, position_id, ts, qty, price, kind)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        params![
            fill_id,
            position.id,
            position.opened_at,
            position.qty,
            position.ref_price,
            "open",
        ],
    )?;
    tx.commit()?;
    Ok(())
}

/// Close an open position by setting `closed_at` + `close_price` and
/// inserting a `'close'` fill.  `fill_id` is the fill row UUID.
pub fn paper_position_close(
    conn: &Connection,
    position_id: &str,
    close_price: f64,
    fill_id: &str,
) -> rusqlite::Result<PaperPosition> {
    let tx = conn.unchecked_transaction()?;

    // Fetch the open position — fails with QueryReturnedNoRows if unknown.
    let pos = paper_position_get(conn, position_id)?
        .ok_or(rusqlite::Error::QueryReturnedNoRows)?;

    let closed_at = now_ms();

    conn.execute(
        "UPDATE paper_positions SET closed_at = ?1, close_price = ?2 WHERE id = ?3",
        params![closed_at, close_price, position_id],
    )?;
    conn.execute(
        "INSERT INTO paper_fills (id, position_id, ts, qty, price, kind)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        params![fill_id, position_id, closed_at, pos.qty, close_price, "close"],
    )?;

    tx.commit()?;

    let updated = paper_position_get(conn, position_id)?
        .expect("position disappeared after close");
    Ok(updated)
}

/// Fetch one position by primary key. Returns `None` when unknown.
pub fn paper_position_get(
    conn: &Connection,
    id: &str,
) -> rusqlite::Result<Option<PaperPosition>> {
    let result = conn.query_row(
        "SELECT id, symbol, side, qty, ref_price, opened_at, closed_at, close_price
         FROM paper_positions WHERE id = ?1",
        params![id],
        |row| {
            Ok(PaperPosition {
                id: row.get(0)?,
                symbol: row.get(1)?,
                side: row.get(2)?,
                qty: row.get(3)?,
                ref_price: row.get(4)?,
                opened_at: row.get(5)?,
                closed_at: row.get(6)?,
                close_price: row.get(7)?,
            })
        },
    );
    match result {
        Ok(r) => Ok(Some(r)),
        Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
        Err(e) => Err(e),
    }
}

/// Return all positions, open ones first (ordered by `opened_at ASC`).
pub fn paper_position_list(conn: &Connection) -> rusqlite::Result<Vec<PaperPosition>> {
    let mut stmt = conn.prepare(
        "SELECT id, symbol, side, qty, ref_price, opened_at, closed_at, close_price
         FROM paper_positions
         ORDER BY closed_at IS NOT NULL ASC, opened_at ASC",
    )?;
    let rows = stmt.query_map([], |row| {
        Ok(PaperPosition {
            id: row.get(0)?,
            symbol: row.get(1)?,
            side: row.get(2)?,
            qty: row.get(3)?,
            ref_price: row.get(4)?,
            opened_at: row.get(5)?,
            closed_at: row.get(6)?,
            close_price: row.get(7)?,
        })
    })?
    .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

/// Return all fills for a position, ordered by `ts ASC`.
pub fn paper_fills_list(
    conn: &Connection,
    position_id: &str,
) -> rusqlite::Result<Vec<PaperFill>> {
    let mut stmt = conn.prepare(
        "SELECT id, position_id, ts, qty, price, kind
         FROM paper_fills
         WHERE position_id = ?1
         ORDER BY ts ASC",
    )?;
    let rows = stmt.query_map(params![position_id], |row| {
        Ok(PaperFill {
            id: row.get(0)?,
            position_id: row.get(1)?,
            ts: row.get(2)?,
            qty: row.get(3)?,
            price: row.get(4)?,
            kind: row.get(5)?,
        })
    })?
    .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::run_migrations;

    fn fresh_db() -> Connection {
        let conn = Connection::open_in_memory().expect("in-memory db");
        // Enable FK enforcement — required for ON DELETE CASCADE.
        conn.execute_batch("PRAGMA foreign_keys = ON;").expect("FK pragma");
        run_migrations(&conn).expect("migrations");
        conn
    }

    // -----------------------------------------------------------------------
    // ResearchNote tests
    // -----------------------------------------------------------------------

    fn make_note(id: &str, title: &str) -> ResearchNote {
        ResearchNote {
            id: id.to_string(),
            title: title.to_string(),
            body: format!("Body of {title}"),
            tags_json: r#"["DeFi","momentum"]"#.to_string(),
            symbol: Some("BTC".to_string()),
            timeframe: Some("1h".to_string()),
            created_at: 1_700_000_000_000,
        }
    }

    #[test]
    fn test_research_note_insert_list_get_delete() {
        let conn = fresh_db();
        research_note_insert(&conn, &make_note("n1", "Alpha")).expect("insert n1");
        research_note_insert(&conn, &make_note("n2", "Beta")).expect("insert n2");

        let list = research_note_list(&conn).expect("list");
        assert_eq!(list.len(), 2);
        // Most-recent first by created_at DESC — both have same ts so order may vary,
        // but both must be present.
        assert!(list.iter().any(|n| n.id == "n1"));
        assert!(list.iter().any(|n| n.id == "n2"));

        let got = research_note_get(&conn, "n1").expect("get").expect("found");
        assert_eq!(got.title, "Alpha");
        assert_eq!(got.tags_json, r#"["DeFi","momentum"]"#);
        assert_eq!(got.symbol.as_deref(), Some("BTC"));

        research_note_delete(&conn, "n1").expect("delete n1");
        assert_eq!(research_note_list(&conn).unwrap().len(), 1);

        // Deleting non-existent id is a no-op.
        research_note_delete(&conn, "does-not-exist").expect("delete missing");
    }

    #[test]
    fn test_research_note_get_missing_returns_none() {
        let conn = fresh_db();
        let result = research_note_get(&conn, "ghost").expect("no error");
        assert!(result.is_none());
    }

    // -----------------------------------------------------------------------
    // AiDataset tests
    // -----------------------------------------------------------------------

    fn make_ai_dataset(id: &str, sym: &str, kind: &str) -> AiDataset {
        AiDataset {
            id: id.to_string(),
            name: format!("Dataset {id}"),
            symbol: sym.to_string(),
            timeframe: "1h".to_string(),
            kind: kind.to_string(),
            values_json: "[1.0,2.0,3.0]".to_string(),
            source: "ai".to_string(),
            created_at: 1_700_000_000_000,
        }
    }

    #[test]
    fn test_ai_dataset_insert_list_get_delete() {
        let conn = fresh_db();
        ai_dataset_insert(&conn, &make_ai_dataset("d1", "BTC", "overlay")).expect("insert d1");
        ai_dataset_insert(&conn, &make_ai_dataset("d2", "ETH", "series")).expect("insert d2");

        let list = ai_dataset_list(&conn).expect("list");
        assert_eq!(list.len(), 2);

        let got = ai_dataset_get(&conn, "d1").expect("get").expect("found");
        assert_eq!(got.kind, "overlay");
        assert_eq!(got.symbol, "BTC");
        assert_eq!(got.values_json, "[1.0,2.0,3.0]");

        // Round-trip: source field preserved.
        assert_eq!(got.source, "ai");

        ai_dataset_delete(&conn, "d1").expect("delete");
        assert_eq!(ai_dataset_list(&conn).unwrap().len(), 1);

        ai_dataset_delete(&conn, "does-not-exist").expect("delete missing");
    }

    #[test]
    fn test_ai_dataset_get_missing_returns_none() {
        let conn = fresh_db();
        assert!(ai_dataset_get(&conn, "x").expect("no error").is_none());
    }

    // -----------------------------------------------------------------------
    // Strategy + revision tests (the core append-only invariant)
    // -----------------------------------------------------------------------

    fn make_strategy(id: &str, name: &str, body: &str) -> AiStrategy {
        AiStrategy {
            id: id.to_string(),
            name: name.to_string(),
            body_json: body.to_string(),
            current_revision: 1,
            created_at: 1_700_000_000_000,
            updated_at: 1_700_000_000_000,
        }
    }

    /// Canonical Strategy DSL round-trip sample — mirrors the shape defined in
    /// `src/ai/schemas.ts` (Strategy Zod schema, lines 131–144).
    fn sample_strategy_json(id: &str) -> String {
        format!(
            r#"{{
              "id": "{id}",
              "name": "RSI Mean-Revert",
              "thesis": "Buy oversold, sell overbought via RSI(14).",
              "rules": {{
                "entry": [
                  {{"indicator":"rsi","op":"<","value":30,"params":{{"period":14}}}}
                ],
                "exit": [
                  {{"indicator":"rsi","op":">","value":70,"params":{{"period":14}}}}
                ]
              }},
              "perf": null,
              "version": 1,
              "createdAt": 1700000000000
            }}"#
        )
    }

    #[test]
    fn test_strategy_insert_list_get_delete() {
        let conn = fresh_db();
        let body = sample_strategy_json("s1");
        let strat = make_strategy("s1", "RSI Mean-Revert", &body);
        strategy_insert(&conn, &strat, "rev-s1-1").expect("insert strategy");

        let list = strategy_list(&conn).expect("list");
        assert_eq!(list.len(), 1);
        let got = strategy_get(&conn, "s1").expect("get").expect("found");
        assert_eq!(got.name, "RSI Mean-Revert");
        assert_eq!(got.current_revision, 1);
        assert!(got.body_json.contains("RSI Mean-Revert"));

        // Revision row created alongside the strategy.
        let revs = strategy_revisions_list(&conn, "s1").expect("revisions");
        assert_eq!(revs.len(), 1);
        assert_eq!(revs[0].rev, 1);

        strategy_delete(&conn, "s1").expect("delete");
        assert!(strategy_list(&conn).unwrap().is_empty());
    }

    #[test]
    fn test_strategy_get_missing_returns_none() {
        let conn = fresh_db();
        assert!(strategy_get(&conn, "ghost").expect("no error").is_none());
    }

    /// ADR-0005 invariant: N edits produce N+1 revision rows.
    #[test]
    fn test_update_strategy_produces_n_plus_one_revisions() {
        let conn = fresh_db();
        let body_v1 = sample_strategy_json("s2");
        let strat = make_strategy("s2", "Donchian Breakout", &body_v1);
        strategy_insert(&conn, &strat, "rev-s2-1").expect("insert");

        // Edit 1 → revision 2.
        let body_v2 = body_v1.replace("RSI Mean-Revert", "Donchian v2");
        let updated = strategy_update(&conn, "s2", &body_v2, "rev-s2-2").expect("update 1");
        assert_eq!(updated.current_revision, 2);
        assert!(updated.body_json.contains("Donchian v2"));

        // Edit 2 → revision 3.
        let body_v3 = body_v2.replace("Donchian v2", "Donchian v3");
        let updated2 = strategy_update(&conn, "s2", &body_v3, "rev-s2-3").expect("update 2");
        assert_eq!(updated2.current_revision, 3);

        // N = 2 edits → N+1 = 3 total revision rows.
        let revs = strategy_revisions_list(&conn, "s2").expect("revisions");
        assert_eq!(revs.len(), 3, "2 edits → 3 revision rows (N+1 invariant)");
        assert_eq!(revs[0].rev, 1);
        assert_eq!(revs[1].rev, 2);
        assert_eq!(revs[2].rev, 3);
    }

    /// Append-only: existing revision rows must never be mutated.
    #[test]
    fn test_update_strategy_does_not_mutate_old_revisions() {
        let conn = fresh_db();
        let body_v1 = sample_strategy_json("s3");
        strategy_insert(
            &conn,
            &make_strategy("s3", "Volatile RSI", &body_v1),
            "rev-s3-1",
        )
        .expect("insert");

        let body_v2 = body_v1.replace("RSI Mean-Revert", "Volatile RSI v2");
        strategy_update(&conn, "s3", &body_v2, "rev-s3-2").expect("update");

        let revs = strategy_revisions_list(&conn, "s3").expect("revisions");
        // Rev 1 still holds the original body — immutable.
        assert!(
            revs[0].body_json.contains("RSI Mean-Revert"),
            "rev 1 must remain unchanged after update"
        );
        // Rev 2 holds the new body.
        assert!(revs[1].body_json.contains("Volatile RSI v2"));
    }

    /// Deleting a strategy must cascade to its revision rows (FK ON DELETE CASCADE).
    #[test]
    fn test_delete_strategy_cascades_to_revisions() {
        let conn = fresh_db();
        let body = sample_strategy_json("s4");
        strategy_insert(
            &conn,
            &make_strategy("s4", "Cascade Test", &body),
            "rev-s4-1",
        )
        .expect("insert");
        strategy_update(&conn, "s4", &body.replace("RSI Mean-Revert", "v2"), "rev-s4-2")
            .expect("update");

        // Sanity: 2 revisions before delete.
        let before = strategy_revisions_list(&conn, "s4").expect("before");
        assert_eq!(before.len(), 2);

        // Delete the strategy head → must cascade.
        strategy_delete(&conn, "s4").expect("delete");

        // The head row is gone.
        assert!(strategy_get(&conn, "s4").expect("get").is_none());

        // All revision rows must be gone too.
        let after: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM strategy_revisions WHERE strategy_id = 's4'",
                [],
                |r| r.get(0),
            )
            .expect("count revisions");
        assert_eq!(after, 0, "cascade delete must remove all revision rows");
    }

    // -----------------------------------------------------------------------
    // PaperPosition + PaperFill tests
    // -----------------------------------------------------------------------

    fn make_position(id: &str, sym: &str, side: &str) -> PaperPosition {
        PaperPosition {
            id: id.to_string(),
            symbol: sym.to_string(),
            side: side.to_string(),
            qty: 1.5,
            ref_price: 50_000.0,
            opened_at: 1_700_000_000_000,
            closed_at: None,
            close_price: None,
        }
    }

    #[test]
    fn test_paper_position_open_and_list() {
        let conn = fresh_db();
        paper_position_open(&conn, &make_position("p1", "BTC", "long"), "f1").expect("open p1");
        paper_position_open(&conn, &make_position("p2", "ETH", "short"), "f2").expect("open p2");

        let list = paper_position_list(&conn).expect("list");
        assert_eq!(list.len(), 2);
        assert!(list.iter().all(|p| p.closed_at.is_none()), "all open");

        // Each position has exactly one 'open' fill.
        let fills_p1 = paper_fills_list(&conn, "p1").expect("fills p1");
        assert_eq!(fills_p1.len(), 1);
        assert_eq!(fills_p1[0].kind, "open");
        assert!((fills_p1[0].price - 50_000.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_paper_position_close() {
        let conn = fresh_db();
        paper_position_open(&conn, &make_position("p3", "BTC", "long"), "f3").expect("open");

        let closed = paper_position_close(&conn, "p3", 55_000.0, "f3-close").expect("close");
        assert!(closed.closed_at.is_some());
        assert!((closed.close_price.unwrap() - 55_000.0).abs() < f64::EPSILON);

        // Verify fills: 'open' then 'close'.
        let fills = paper_fills_list(&conn, "p3").expect("fills");
        assert_eq!(fills.len(), 2);
        assert_eq!(fills[0].kind, "open");
        assert_eq!(fills[1].kind, "close");
        assert!((fills[1].price - 55_000.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_paper_position_get_missing_returns_none() {
        let conn = fresh_db();
        assert!(paper_position_get(&conn, "ghost").expect("no error").is_none());
    }

    #[test]
    fn test_paper_fills_cascade_delete() {
        let conn = fresh_db();
        paper_position_open(&conn, &make_position("p4", "SOL", "long"), "f4").expect("open");
        paper_position_close(&conn, "p4", 200.0, "f4-close").expect("close");

        let fills_before: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM paper_fills WHERE position_id = 'p4'",
                [],
                |r| r.get(0),
            )
            .expect("count");
        assert_eq!(fills_before, 2);

        // Delete the position — fills must cascade.
        conn.execute("DELETE FROM paper_positions WHERE id = 'p4'", [])
            .expect("delete position");

        let fills_after: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM paper_fills WHERE position_id = 'p4'",
                [],
                |r| r.get(0),
            )
            .expect("count after");
        assert_eq!(fills_after, 0, "cascade must remove fills");
    }

    // -----------------------------------------------------------------------
    // Round-trip serialisation checks (mirrors src/ai/schemas.ts shapes)
    // -----------------------------------------------------------------------

    /// Deserialise a sample Strategy JSON and re-serialise it — verifies the
    /// Rust `AiStrategy.body_json` field can hold the canonical shape without
    /// loss.  The TS `Strategy` Zod schema is the source of truth (lines
    /// 131-144 of `src/ai/schemas.ts`); we just verify the JSON is valid and
    /// round-trips cleanly as a string field (no Rust schema validation needed
    /// at this layer — validation lives in the TS tool handler).
    #[test]
    fn test_strategy_body_json_roundtrip() {
        let conn = fresh_db();
        let body = sample_strategy_json("rt1");
        // Parse to verify it is valid JSON.
        let parsed: serde_json::Value = serde_json::from_str(&body).expect("valid JSON");
        assert_eq!(parsed["version"], 1);
        assert!(parsed["rules"]["entry"].is_array());
        assert!(parsed["rules"]["exit"].is_array());

        strategy_insert(
            &conn,
            &make_strategy("rt1", "Round-trip", &body),
            "rev-rt1-1",
        )
        .expect("insert");

        let got = strategy_get(&conn, "rt1").expect("get").expect("found");
        let got_parsed: serde_json::Value =
            serde_json::from_str(&got.body_json).expect("body_json valid JSON");
        assert_eq!(got_parsed["id"].as_str().unwrap(), "rt1");
        assert_eq!(got_parsed["version"], 1);
    }

    /// Deserialise a sample Dataset JSON blob to verify the `ai_datasets`
    /// table can hold the canonical `Dataset` shape (src/ai/schemas.ts lines
    /// 146-170).
    #[test]
    fn test_ai_dataset_values_json_roundtrip() {
        let conn = fresh_db();
        let values: Vec<Option<f64>> = vec![Some(1.0), Some(2.5), None, Some(4.0)];
        let values_json = serde_json::to_string(&values).expect("serialise values");

        let ds = AiDataset {
            id: "ds-rt".to_string(),
            name: "SMA(20) on BTC".to_string(),
            symbol: "BTC".to_string(),
            timeframe: "1h".to_string(),
            kind: "overlay".to_string(),
            values_json: values_json.clone(),
            source: "ai".to_string(),
            created_at: 1_700_000_000_000,
        };
        ai_dataset_insert(&conn, &ds).expect("insert");
        let got = ai_dataset_get(&conn, "ds-rt").expect("get").expect("found");

        // Re-parse and verify nulls are preserved.
        let got_values: Vec<Option<f64>> =
            serde_json::from_str(&got.values_json).expect("parse values_json");
        assert_eq!(got_values.len(), 4);
        assert!(got_values[2].is_none(), "null preserved through DB round-trip");
        assert!((got_values[3].unwrap() - 4.0).abs() < f64::EPSILON);
    }
}
